#!/bin/bash

# Install Java
apt-get update && apt-get install -y openjdk-11-jdk

# Set JAVA_HOME
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
export PATH=$JAVA_HOME/bin:$PATH

# Download and extract Apache Lucene
wget https://downloads.apache.org/lucene/java/9.1.0/lucene-9.1.0.tgz
tar -xzf lucene-9.1.0.tgz